[profile.default]
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
optimizer = true
optimizer_runs = 200
cache = true
cache_path = "cache"
broadcast = "broadcast"
solc = "0.8.28"
gas_reports = ["*"]
threads = 0
extra_output = ["metadata", "abi"]
